toolforge:
    intuition:
        domain: 'global-search'
    oauth:
        consumer_key: '%env(OAUTH_KEY)%'
        consumer_secret: '%env(OAUTH_SECRET)%'
        logged_in_user: '%env(LOGGED_IN_USER)%'
